---
title: "Kahve Notlarım"
author: "Emre Toros"
date: "27.12.2022"
output:
  html_document:
    theme: paper
    highlight: kate
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, fig.showtext = T, fig.retina = 1)
```

```{r prep, message=FALSE}

## packages
library(tidyverse)
library(ggdist)
library(grid)
library(png)
library(ggtext)
library(ragg)
library(pdftools)
library(extrafont)

## ggplot theme
theme_set(theme_minimal(base_family = "Bebas Neue", base_size = 16))

theme_update(
  panel.grid = element_blank(),
  axis.title = element_blank(),
  axis.text = element_blank(),
  plot.background = element_rect(color = NA, fill = "#faf9f5")
)
```

```{r data}
df_coffee <- readxl::read_excel("tor_data.xlsx")


```

```{r data-prep}

df_coffee_p <-
  df_coffee %>% 
  filter(Not != 0) %>% 
  group_by(Kahve, Kıta, Ülke, Kavrumhane, Tarih, Not) %>% 
  summarize(Not = mean(Not, na.rm = T)) %>% 
  group_by(Ülke) %>%
  filter(n() >= 2) %>%
  mutate(#
    mean = mean(Not),
    max = max(Not),
    min = min(Not),
    n = n())%>% 
  ungroup() %>% 
  mutate(
    Ülke = fct_reorder(Ülke, mean),
    y = as.numeric(Ülke))

```

```{r plot, fig.width = 12.5, fig.height = 9}

img <- readPNG(here::here("img", "coffee.png"))
r <- rasterGrob(img, interpolate = TRUE)

df_coffee_sum <- 
  df_coffee_p %>% 
  group_by(Ülke)  %>% 
  slice(1)


ggplot(df_coffee_p, aes(
  Not, 
  y = y
)) + 
  annotation_custom(r, xmin = 75, xmax = 110, ymin = 0, ymax = 15) +
  ## labels countries
  geom_text(
    data = df_coffee_sum,
    aes(
      x = min, 
      y = y,
      label = Ülke
    ),
    family = "Fira Sans",
    color = "black",
    #fontface = "bold",
    vjust = -0.35,
    hjust = -0.2
  ) +
  
  ## stripe
  stat_interval(
    aes(y = y - .1),
    orientation = "horizontal",
    .width = c(.25, .5, .95, 1),
    stroke = 0,
    size = 1.3 ) +
  
  ## indicator mean
  geom_point(
    data = df_coffee_sum,
    aes(x = mean + .01, y = y - 0.3),
    shape = 2,
    color = "firebrick",
    size = 1.7
  ) + 
  geom_text(
    data = df_coffee_sum,
    aes(
      x = mean + .17, 
      y = y - .11,
      label = glue::glue("{round(mean, 1)} puan") 
    ),
    family = "Fira Sans",
    color = "firebrick",
    size = 3,
    vjust = 1.5,
    hjust = 0
  ) +
  
  ## indicator minimum
  geom_point(
    data = df_coffee_sum,
    aes(x = min + .01, y = y - 0.3),
    shape = 2,
    color = "firebrick",
    size = 1.7
  ) + 
  geom_text(
    data = df_coffee_sum,
    aes(
      x = min + .17, 
      y = y - .11,
      label = glue::glue("{round(min, 1)} puan") 
    ),
    family = "Fira Sans",
    color = "firebrick",
    size = 3,
    vjust = 1.5,
    hjust = 0
  ) +
  
## indicator maximum
geom_point(
    data = df_coffee_sum,
    aes(x = max + .01, y = y - 0.3),
    shape = 2,
    color = "firebrick",
    size = 1.7
  ) + 
  geom_text(
    data = df_coffee_sum,
    aes(
      x = max + .17, 
      y = y - .11,
      label = glue::glue("{round(max, 1)} puan") 
    ),
    family = "Fira Sans",
    color = "firebrick",
    size = 3,
    vjust = 1.5,
    hjust = 0
  ) +
  
  
  ## dots
  stat_dots(
    quantiles = NA,
    orientation = "vertical",
    normalize = "none",
    scale = 0.7,
    color = "#6f4e37",
    fill = "#6f4e37"
  ) +
  ## labels axis
  geom_text(
    data = tibble(
      x = seq(60, 90, by = 10),
      y = 0.5,
      label = glue::glue("{seq(60, 90, by = 10)} puan")
    ),
    aes(
      x = x, 
      y = y,
      label = label
    ),
    inherit.aes = F,
    family = "Fira Sans",
    color = "black",
    size = 3.5
  ) +
  geom_point(
    data = tibble(
      x = rep(seq(60, 90, by = 10), 2),
      y = rep(c(8.55, 8.22), each = 4)
    ),
    aes(
      x = x, 
      y = y
    ),
    inherit.aes = F,
    color = "black",
    shape = "|",
    size = 1
  ) +
  
  ## label text
  geom_textbox(
    data = tibble(
      x = 64.5,
      y = 9.2,
      label = "<b style='font-size:24pt;'>Kahve Notlarım...</b><br><br> 3 yıldır içtiğim kahveleri 100 puan üzerinden koku, asidite, şeker, gövde ve bitiş kriterleri üzerinden notlandırıyorum. Bu grafikte iki veya daha çok çekirdeğini denediğim ülkeler var. Ülkelere ait şeritlerin renkleri çekirdeklerin 100 puan üzerinden düştükleri dilimleri gösteriyor (<b style='color:#6F2808;'>%25</b>, <b style='color:#CE711B;'>%50</b>, <b style='color:#AE9760;'> %95</b>, ve <b style='color:#A3A3A3;'>%100</b>). Puanların 60 ila 88 arasında değiştiğini görüyoruz. Şeritlerin üstündeki yuvarlaklar çekirdekleri, altınaki üçgenler sırası ile en düşük, medyan ve en yüksek puanları gösteriyor.<br><br><i style='color:#99754d;'> @emretoros via Cédric Scherer </i><br><i style='font-size:5pt;color:#99754d;'>Coffee stain: 
© paperwork.</i>
"
    ),
    aes(
      x = x, y = y, label = label
    ),
    inherit.aes = F,
    family = "Fira Sans",
    size = 4,
    lineheight = 1.5,
    width = unit(3.8, "inch"),
    fill = NA,
    box.colour = NA,
    hjust = .5,
    vjust = 0
  ) +
  scale_x_continuous(
    breaks = seq(60, 90, by = 10),
    labels = function(x) paste0(x, " points")
  ) +
  scale_y_continuous(expand = c(0, 0)) +
  scale_color_manual(
    values = c("grey85", "#ccbe9b", "#e8984e", "#94350b"),
    guide = F
  ) +
  scale_size(
    range = c(8.75, 15.5),
    guide = F
  ) 


```
